---
title: "Workshop"
author: "Hector Zumbado"
format: html
editor: visual
---

## Goal

We will create different static maps, interactive maps map and graphs describing the distribution of the desert sand verbena ([*Abronia villosa*](https://www.calflora.org/app/taxon?crn=21)) in the US, California, and Riverside County.

Steps

1.  Tutorial 1: how to create and configure R projects with '***renv***' (demonstration).

2.  Tutorial 2: Set up GBIF account in RStudio.

3.  Tutorial 3: Set up GitHub account in R studio. Use document 'Set GitHub in RStudio'.

4.  how to create and configure R projects with '***renv***' from the terminal (demonstration).

5.  Create new project in R studio using GitHub and renv boxes.

    Create a new project in your workshop folder named demo1.

    Check **GitHub** and **renv** boxes.

    Copy and paste the 'structure' script within your project. Run the script.

    Open a new file and write library(rgbif).

    Save file as 00-download_data.

    Restart R project and install using renv.

    Check renv::status() and create snapshop with renv::snapshot().

    Create a project with the Demo1 name in GitHub

    Link Rstudio and GitHub with SSH protocol.

    Check remote connection and branch.

    Stage, commit, and push repository to github.

6.  Fork project <https://github.com/hzumbado/ccc_workshop>

7.  Keep the same name

8.  Clone project to your computer using the version control and SSH protocol

9.  Save project (workshop folder)

    Check remote connection and branch in the terminal
